### ISSUE TITLE
PLS-00201: identifier 'AX_PLG_SPINKIT_PKG.SPINKIT' must be declared

### ISSUE THREAD

**Issue by Samraw003** [isabolic/apex-plg-spinkit#1]
Hi,

I am encountering following error on Apex 5.1

Can you please help?

Error in PLSQL code raised during plug-in processing.

ORA-06550: line 4, column 55: PLS-00201: identifier 'AX_PLG_SPINKIT_PKG.SPINKIT' must be declared ORA-06550: line 4, column 1: PL/SQL: Statement ignored

Thanks 
Sammeer

**Comment by isabolic** [comment]
@Samraw003 HI

did you compile AX_PLG_SPINKIT_PKG.PKS and AX_PLG_SPINKIT_PKG.PKB in your application parsing schema?

best regards
isabolic
